### PR TITLE
- Fix: wrap: false returning inconsistent data types

### LINKED ISSUE #98: `wrap: false` does not correctly return some cases
The following queries provide results that do not match those of other implementations of JSONPath
(compare https://github.com/cburgmer/json-path-comparison/tree/master/comparison):

- [ ] `$[-1:]`
  Input:
  ```
  ["first", "second", "third"]
  ```
  Expected output:
  ```
  ["third"]
  ```
  Actual output:
  ```
  "third"
  ```

- [ ] `$[0:1]`
  Input:
  ```
  ["first", "second"]
  ```
  Expected output:
  ```
  ["first"]
  ```
  Actual output:
  ```
  "first"
  ```

- [ ] `$.key`
  Input:
  ```
  {"key": ["first", "second"]}
  ```
  Expected output:
  ```
  ["first", "second"]
  ```
  Actual output:
  ```
  [["first", "second"]]
  ```

For reference, the output was generated by the program in https://github.com/cburgmer/json-path-comparison/tree/master/implementations/JavaScript_jsonpath-plus.

### PR DESCRIPTION
**Pull request by CacheControl**
Fixes #98 - consistently detect and return arrays vs scalars.

The following paths return whatever is found at the specified location whether that is a scalar, object, or array:
 *   "store.book[0]" - specific book
 *   "store.bicycle.red" - single property of a single object
 
The following paths will always result in an array, because they may generate multiple results depending on the dataset:
 *   $.store.book[0][category,author] - property or index lists return multiple values
 *   $..book - ".." will recurse through the store object
 *   $.store.book[1:2] - indicates a range within the array
 *   $.store.book[*] - wild card indicates multiple results
 *   $.store.book[?(@.isbn)] - filtering

@brettz9 would you mind reviewing this please?

### CODE REVIEW

**Comment by brettz9** [comment]
@CacheControl : Thank you so much for doing this! I think if we can get this done, it will be well appreciated by many. I have a few implementation changes I intend to ask for inline shortly, but I also hope others may take a look and at least check that the changes to the tests are reasonable per their expectations.

While it looks like the comparison is done with `wrap: true` instead (see https://github.com/cburgmer/json-path-comparison/blob/master/implementations/JavaScript_jsonpath-plus/index.js#L23 ), I wonder if looking at the [comparisons](https://cburgmer.github.io/json-path-comparison/) can still help get an idea of what should be expected if the other implementations offered `wrap: false` as an option? I'd also suggest taking a look at https://github.com/cburgmer/json-path-comparison/blob/master/OPEN_QUESTIONS.md and seeing if that analysis affects your approach.

File: src/jsonpath.js [hunk 1]
```diff
@@ -363,6 +363,45 @@ JSONPath.prototype._getPreferredOutput = function (ea) {
...
+ * @returns {boolean}
+ */
+JSONPath.prototype.isSingularResult = function (result, exprList) {
+    return (result.length === 1 &&
+             !exprList.includes('*') &&
+             !exprList.includes('..') &&
+              exprList.every((loc) => !this.isFilterExpr(loc)) &&
+              exprList.every((loc) => !loc.includes(',')) &&
+              exprList.every((loc) => !loc.includes(':')));
+};
```
Comment (brettz9) [inline src/jsonpath.js]: Unless a method is expected to need to reference instance-specific properties, I'd like for us to implement such as these as class methods (e.g., `JSONPath.isFilterExpr` instead of `JSONPath.prototype.isFilterExpr`). This practice allows for using such methods without needing to set up an instance, and also quickly conveys a distinction of purpose.

If you run the `eslint` script, this is one of the issues you'll see reported--as built-in eslint rule [class-methods-use-this](https://eslint.org/docs/rules/class-methods-use-this) (and any others ought to be fixed as well).

However, before making such a change, I am wondering whether it would be more efficient to pass on information about the filter type during iterating (e.g., passing on an `isFilter` boolean similar to what we do with `parent` and `parentPropName` in calls to `_walk`) rather than having to cycle through each expression again?

If possible, I'd also recommend trying with https://github.com/andykais/json-querying-performance-testing to see the impact before and after.

Comment (CacheControl) [reply src/jsonpath.js]: @brettz9 good feedback! yes passing a property along while doing the recursion feels much cleaner. I've pushed a commit that takes this approach. Let me know if you'd like any further adjustments.

Next I'm going to do a deep dive on the updated regression tests that @cburgmer just pushed (thanks!), and vet each use case. I'll post my findings.

Comment (brettz9) [reply src/jsonpath.js]: Great, looks very good from my eyeballing... As far as your deep dive on the regression tests, let me know when those tests may only be indicating separate issues, and I can try out and take a final look at this PR. (Though if you find you may be closing to fixing any other issues, we can see about putting them into the same major release, so any other breakage can be handled in one version bump.)

Comment (CacheControl) [reply src/jsonpath.js]: @brettz9 I (finally) carved out some time to perform the qa. I went through all the `scalar-consensus` scenarios in the json-path-comparison [regression suite](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml), and validated that (excepting current bugs) `wrap:false` aligns with other libraries. Below are my notes:

| Scalar Rule  | Passes? | Notes  |
| ------------- | ------------- | ------------- |
| [$[2]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L13)  | Yes  |   |
| [$.2](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L21)  | Yes  |   |
| [$[0]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L26)  | Yes  |   |
| [$[-1]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L31)  | No  | Existing issue; see [bug report](https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/JavaScript_jsonpath-plus.md)   |
| [$['key']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L137)  | Yes  |   |
| [$['@']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L149)  | No  |   Existing issue; see [bug report](https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/JavaScript_jsonpath-plus.md)|
| [$['$']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L154)  | Yes  |   Existing issue; see [bug report](https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/JavaScript_jsonpath-plus.md)|
| [$['two.some']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L159)  | Yes  |   
| [$['special:"chars']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L187)  | Yes  |   |
| [$['*']](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L192)  | No  | Existing issue; see [bug report](https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/JavaScript_jsonpath-plus.md)  |
| [$.key](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L209)  | Yes  |   |
| [$.key](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L214) (on array)  | Yes  |   |
| [$.key](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L219) (on null)  | Yes  |   |
| [$.key](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L219) (on null)  | Yes  |   |
| [$](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L263)  | Yes  |   |

I also reviewed the [test cases](https://github.com/cburgmer/json-path-comparison/blob/JavaScript_jsonpath-plus_nowrap/bug_reports/JavaScript_jsonpath-plus_nowrap.md) generated against the current wrap:false implementation. This confirmed the fixes introduced by this pr, where we're returning a scalar when an array is, in fact, appropriate:

| Scalar Rule  | Passes? | Notes  |
| ------------- | ------------- | ------------- |
| [$[*].bar[*].baz](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L284)  | Yes  |   |
| [$["key"]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L164)  | no consensus  | -  |
| [$[?(@.key)]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L127)  | Yes  |   |
| [$[?(@.key==42)]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L100)  | Yes  |   |
| [$[0:1]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L85)  | Yes  |   |
| [$[0:0]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L81)  | No  |   Existing issue; see [bug report](https://github.com/cburgmer/json-path-comparison/blob/master/bug_reports/JavaScript_jsonpath-plus.md)|
| [$[-1:]](https://github.com/cburgmer/json-path-comparison/blob/master/regression_suite/regression_suite.yaml#L40)  | Yes  |  |

phew! 😅 I'm feeling confident at this point that these changes aligns us with the `scalar consensus` for all other libraries, and also fixes a lot of cases where `wrap:false` is returning an array when it should not 🎉

**Comment by brettz9** [comment]
This is great to have! Thanks so much for your work on this!

I'm bumping to a new major version as the new changes may be unexpected for some.

Due to being on a slow connection where I am, I have not been able to download the dependencies to run the json path comparison suite on my own (nor the performance suite), but it looks good, and as mentioned, with a major version bump, it should give a chance for others to adjust or report back if there are concerns.

I've also added testing coverage, and some further tests. I plan to make a new release shortly, after seeing about getting some further coverage.

**Comment by brettz9** [comment]
Released as part of v3.0.0 along with a few other fixes discovered in the process of getting to 100% coverage.

Despite adding new tests, some of even these new tests may need to be revised to harmonize with cross-implementation behavior (e.g., as with the scalar differences discussed), but at least now we are specifying the current behavior more fully in our tests so upon refactoring, we can detect regressions as well as more easily specify any new breaking changes in behavior by simply refactoring existing tests.

**Comment by jorchg** [comment]
@brettz9 Will you publish v3.0.0 to npm? Thank you for the great job :D

**Comment by CacheControl** [comment]
@brettz9 if you're hoping to squeeze a few more breaking changes into this release, would you mind publishing a release candidate of 3.0? that way I can expedite the bug fix on the json-rules-engine side of things. thank you!

**Comment by brettz9** [comment]
Sorry, @CacheControl , I thought I had published it! Done! (Probably will be future breaking changes, at least for changing TypeScript if someone can help with #113 )

**Comment by brettz9** [comment]
And sorry @jorchg , I guess I had thought it was already released or hadn't seen your message for some reason. But I see it on npm now.

**Comment by jorchg** [comment]
> And sorry @jorchg , I guess I had thought it was already released or hadn't seen your message for some reason. But I see it on npm now.

So cool @brettz9. No problem at all. Thank you for your effort!

And thank you also to @CacheControl :)
